print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/buhlerfamily/Desktop/Chrystel/BackUp/Bear_Game/Bear_Prototypes/Assets/Holy_WalkWay1.mb"`)
{		
	file -o "/Users/buhlerfamily/Desktop/Chrystel/BackUp/Bear_Game/Bear_Prototypes/Assets/Holy_WalkWay1.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/buhlerfamily/Desktop/Chrystel/BackUp/Bear_Game/Bear_Prototypes/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/buhlerfamily/Desktop/Chrystel/BackUp/Bear_Game/Bear_Prototypes/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/buhlerfamily/Desktop/Chrystel/BackUp/Bear_Game/Bear_Prototypes/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
